version: '3.3'
services:

  home.postgres:
    image: postgres:latest
    container_name: home.postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 7000:5432
    volumes:
      - "$HOME/docker/home/postgres:/var/lib/postgresql/data"
      - "$HOME/docker/home/log:/var/log/postgres"
    networks:
      default:
        aliases:
          - home.postgres

  rabbitmq.simple:
    image: home.rabbitmq
    container_name: home.rabbitmq
    hostname: home.rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "dev"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "${DOCKER_ENV_DEV_RABBITMQ_DATA_PATH}:/var/lib/rabbitmq:rw"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      default:
        aliases:
          - home.rabbitmq
volumes:
  esdata1:
    driver: local
