version: '3.3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "$HOME/docker/home/postgres:/var/lib/postgresql/data"
      - "$HOME/docker/home/log:/var/log/postgres"
    networks:
      default:
        aliases:
          - postgres

  gateway:
    image: joaosoft/gateway
    container_name: gateway
    hostname: gateway
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - gateway

  auth:
    image: joaosoft/auth
    container_name: auth
    hostname: auth
    ports:
      - 8001:8001
    networks:
      default:
        aliases:
          - auth

  profile:
    image: joaosoft/profile
    container_name: profile
    hostname: profile
    ports:
      - 8002:8002
    networks:
      default:
        aliases:
          - profile

networks:
  default:
    name: 'bridge'
    driver: 'bridge'
