version: '2.1'
services:
  elasticsearch:
    build:
      context: ./images
      dockerfile: ./elasticsearch.dockerfile
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    build:
      context: ./images
      dockerfile: ./kibana.dockerfile
    volumes:
      - esdata1:/usr/share/kibana/data
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: ./images
      dockerfile: ./logstash.dockerfile
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - esdata1:/usr/share/logstash/data
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local