node.name: devnode
network.host: 0.0.0.0

node.master: true
node.data: true

bootstrap.memory_lock: true

script.inline: false
script.stored: false
script.file:   false

script.engine.painless.inline:          true 
script.engine.painless.stored.search:   true 
script.engine.painless.stored.aggs:     true 
